<?php
/**
 * CsnUser - Coolcsn Zend Framework 2 User Module
 * 
 * @link https://github.com/coolcsn/CsnUser for the canonical source repository
 * @copyright Copyright (c) 2005-2013 LightSoft 2005 Ltd. Bulgaria
 * @license https://github.com/coolcsn/CsnUser/blob/master/LICENSE BSDLicense
 * @author Stoyan Cheresharov <stoyan@coolcsn.com>
 * @author Svetoslav Chonkov <svetoslav.chonkov@gmail.com>
 * @author Nikola Vasilev <niko7vasilev@gmail.com>
 * @author Stoyan Revov <st.revov@gmail.com>
 * @author Martin Briglia <martin@mgscreativa.com>
 */
echo $this->partial('csn-user/layout/nav-menu', array(
    'navMenu' => $this->navMenu,
    'user' => $this->identity()
));

?>

<div class="animate form login_form">
	<section class="login_content">
		<br> <br>
	<?php  echo $this->partial("general-error-ponters")?>
	<img src="<?php  echo $this->basepath("/images/cm.png")?>" width=150 />
		<h2>
    <?php echo sprintf($this->translate('An email has been sent to <span class="zf-green">%s</span>. Please, check your inbox and confirm your request to change password!'), $email);?>
  </h2>
	</section>
</div>
