<?php
echo $this->headtitle('Registration');
/**
 * CsnUser - Coolcsn Zend Framework 2 User Module
 *
 * @link https://github.com/coolcsn/CsnUser for the canonical source repository
 * @copyright Copyright (c) 2005-2013 LightSoft 2005 Ltd. Bulgaria
 * @license https://github.com/coolcsn/CsnUser/blob/master/LICENSE BSDLicense
 * @author Stoyan Cheresharov <stoyan@coolcsn.com>
 * @author Svetoslav Chonkov <svetoslav.chonkov@gmail.com>
 * @author Nikola Vasilev <niko7vasilev@gmail.com>
 * @author Stoyan Revov <st.revov@gmail.com>
 * @author Martin Briglia <martin@mgscreativa.com>
 */

// echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu, 'user' => $this->identity()));
$form = $this->form;

/**
 * Set form fields classes and placeholders here
 */

$form->setAttributes(array(
    'class' => 'form'
));

$form->get('username')->setAttributes(array(
    'class' => 'form-control inpt-form phone',
    
    // 'aria-describedby' => 'basic-addon1',
    'placeholder' => $this->translate('Phone No.')
));

$form->get('email')->setAttributes(array(
    'class' => 'form-control',
    
    'aria-describedby' => 'basic-addon1',
    'placeholder' => $this->translate('Your Email')
));

$form->get('password')->setAttributes(array(
    
    'class' => 'form-control',
    
    'aria-describedby' => 'basic-addon1',
    'placeholder' => $this->translate('Password')
));

$form->get('passwordVerify')->setAttributes(array(
    'class' => 'form-control',
    
    'aria-describedby' => 'basic-addon1',
    'placeholder' => $this->translate('Confirm Password')
));

$form->get('question')->setAttributes(array(
    'class' => 'form-control'
));

$form->get('answer')->setAttributes(array(
    'class' => 'form-control',
    'placeholder' => $this->translate('Type Your Answer')
));

$form->get('submit')->setAttributes(array(
    'class' => 'btn btn-primary btn-block btn-signin',
    'value' => $this->translate('Sign Up')
    // 'style'=>"width: 80%"
));

$form->get('login')->setAttributes(array(
    'class' => 'btn btn btn-warning',
    'label' => $this->translate('Sign In')
));

$form->prepare();

?>

 <?php  //echo $this->partial("general-error-ponters")?>

<div class="col-md-5 p-5 bg-white full-height">
	<div class="login-main-left">
		<div class="text-center mb-5 login-main-left-header pt-4">
                       <?php  echo $this->partial("general-error-ponters")?>
                        <h5 class="mt-3 mb-3">Welcome to Vidoe</h5>
			<!--                         <p>It is a long established fact that a reader <br> will be distracted by the readable.</p> -->
		</div>
                    <?php echo $this->form()->openTag($form); ?>
                        <div class="form-group">
                          <?php echo $this->formLabel($form->get('username'));?>
                          <?php echo $this->formElement($form->get('username'));?>
                          <div style="font-size: 9px; color: red;">
              <?php
            echo $this->formElementErrors($form->get('username'));
            ?>
              </div>
		</div>

		<div class="form-group">
                          <?php //echo $this->formLabel($form->get('email'));?>
                          <?php echo $this->formElement($form->get('email'));?>
                          <div style="font-size: 9px; color: red;">
              <?php
            echo $this->formElementErrors($form->get('email'));
            ?>
              </div>
		</div>

		<div class="form-group">
                           <?php    //echo $this->formLabel($form->get('password')); ?>
                           <?php    echo $this->formPassword($form->get('password')); ?>
                           <div style="font-size: 9px; color: red;">
              <?php
            echo $this->formElementErrors($form->get('password'));
            ?>
              </div>
		</div>

		<div class="form-group">
                           <?php    //echo $this->formLabel($form->get('passwordVerify')); ?>
                           <?php    echo $this->formPassword($form->get('passwordVerify')); ?>
                           <div style="font-size: 9px; color: red;">
              <?php
            echo $this->formElementErrors($form->get('passwordVerify'));
            ?>
              </div>
		</div>

		<div class="mt-4">
			<div class="row">
				<div class="col-12">
                                <?php echo  $this->formSubmit($form->get('submit'))?>
                              </div>
			</div>
		</div>
                     <?php
                    
                    if ($this->messages) {
                        echo '<div style="font-size: 14px; color: red;">' . $this->messages . '</div>';
                        echo '<div style="font-size: 14px; color: red;">' . $this->error . '</div>';
                    }
                    ;
                    ?>
             <?php
            echo $this->formRow($form->get('csrf'));
            echo $this->form()->closeTag();
            ?> 
                     <div class="text-center mt-5">
			<p class="light-gray">
				Already have an account? <a
					href="<?php  echo $this->url('user-index')?>">Sign In</a>
			</p>
		</div>
	</div>
</div>



<!-- signin-box -->







<?php

echo $this->headScript()->appendFile($this->basePath('js/jquery.mask.min.js'))?>


<script type="text/javascript">


        $(document).ready(function () {
            
            $('.phone').mask('00000000000');
           // $('.url').mask('http://#.#', {'translation': {
              //  A: {pattern: /[A-Za-z0-9]/},
              //  S: {pattern: /[A-Za-z]/}
               
             // }
        //});
            

        });

        // for the type of customer
        
    </script>

