<?php
echo $this->headtitle("Reset Password");

// $the_background = " "
// echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>


			
			
<?php
/**
 * CsnUser - Coolcsn Zend Framework 2 User Module
 *
 * @link https://github.com/coolcsn/CsnUser for the canonical source repository
 * @copyright Copyright (c) 2005-2013 LightSoft 2005 Ltd. Bulgaria
 * @license https://github.com/coolcsn/CsnUser/blob/master/LICENSE BSDLicense
 * @author Stoyan Cheresharov <stoyan@coolcsn.com>
 * @author Svetoslav Chonkov <svetoslav.chonkov@gmail.com>
 * @author Nikola Vasilev <niko7vasilev@gmail.com>
 * @author Stoyan Revov <st.revov@gmail.com>
 * @author Martin Briglia <martin@mgscreativa.com>
 */

// echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu, 'user' => $this->identity()));

$form = $this->form;

/**
 * Set form fields classes and placeholders here
 */

$form->setAttributes(array(
    'class' => 'form'
));

$form->get('usernameOrEmail')->setAttributes(array(
    'class' => 'form-control ',
    'placeholder' => $this->translate('Write Your Username or Email')
));

$form->get('captcha')->setAttributes(array(
    'required' => 'true',
    'class' => 'form-control ',
    'placeholder' => $this->translate('Verify you are human')
));

$form->get('submit')->setAttributes(array(
    'class' => 'btn btn btn-success',
    'value' => $this->translate('Send Reset Email')
));
$form->get('login')->setAttributes(array(
    'class' => 'btn btn btn-warning',
    'label' => $this->translate('Sign In')
));

$form->prepare();
?>

<div class="animate form login_form">
	<section class="login_content">
	<br>
	<br>
	<?php  echo $this->partial("general-error-ponters")?>
	<img src="<?php  echo $this->basepath("/images/cm.png")?>" width=150 />

<h1><?php echo $this->translate('Reset Password')?></h1>
          <?php echo $this->form()->openTag($form); ?>
            <div class="row">
				<div class="col-sm-12"> 
                <?php echo $this->message ?>      
              </div>
			</div>
            <?php
            $element = $form->get('usernameOrEmail');
            echo $this->formElement($element);
            echo $this->formElementErrors($element);
            ?>
            <br>
                <?php
                // $element = $form->get('captcha');
                // echo $this->formElement($element);
                // echo $this->formElementErrors($element);
                // ?>
<!--              <br> -->
                <?php echo $this->formRow($form->get('submit'))?>  
                <?php echo $this->formButton($form->get('login'))?>            
             
            <?php
            echo $this->formRow($form->get('csrf'));
            echo $this->form()->closeTag();
            ?>         
       

</section>
</div>