<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'General\Module'                        => __DIR__ . '/Module.php',
    'General\Controller\GeneralController' => __DIR__ . '/src/General/Controller/GeneralController.php',
    'GeneralTest\Framework\TestCase'        => __DIR__ . '/tests/General/Framework/TestCase.php',
    'GeneralTest\SampleTest'                => __DIR__ . '/tests/General/SampleTest.php',
);
