
	
 <?php
$this->headtitle("Login");
$form = $this->form;
$form->setAttribute('action', '' /*$this->url('login') */);
$form->setAttribute('class', 'form-signin');
$form->prepare();

$form->get('usernameOrEmail')->setAttributes(array(
    'class' => 'form-control',
    'placeholder' => $this->translate('Phone Number or Email')
    // 'aria-describedby' => 'basic-addon1'
));

$form->get('password')->setAttributes(array(
    'class' => 'form-control',
    'placeholder' => $this->translate('Password')
    // 'aria-describedby' => 'basic-addon1'
));

$form->get('rememberme')->setAttributes(array(
    'class' => 'col-sm-2'
));
$form->get('submit')->setAttributes(array(
    'class' => 'btn btn-primary btn-block btn-signin',
    // "style" => "width: 80%",
    'value' => $this->translate('Log In')
));

?>



		

			
			
 
	


<div class="col-md-5 p-5 bg-white full-height">
                  <div class="login-main-left">
                     <div class="text-center mb-5 login-main-left-header pt-4">
                        <img src="img/favicon.png" class="img-fluid" alt="LOGO">
                        <h5 class="mt-3 mb-3">Welcome to Video Demo</h5>
<!--                         <p>It is a long established fact that a reader <br> will be distracted by the readable.</p> -->
                     </div>
                    <?php

echo $this->form()->openTag($form);
?>
                        <div class="form-group">
<!--                            <label>Mobile number</label> -->
                           <?php echo $this->formElement()->render($form->get('usernameOrEmail'));?>
                           <div style="font-size: 9px; color: red;">
				<?php echo $this->formElementErrors($form->get('usernameOrEmail')); ?>
				</div>
                        </div>
                        <div class="form-group">
                           
                          <?php echo $this->formElement()->render($form->get('password'));?>
                          <div style="font-size: 9px; color: red;">
<?php echo $this->formElementErrors($form->get('password')); ?></div>
		<div>
                        </div>
                        <div class="mt-4">
                        		
		<?php

echo $this->formRow($form->get('rememberme'));

?>
                           <div class="row">
                              <div class="col-12">
                                 <?php echo  $this->formSubmit($form->get('submit'))?>
                              </div>
                           </div>
                        </div>
                        <?php

if ($this->messages) {
    echo '<div style="font-size: 14px; color: red;">' . $this->messages . '</div>';
    echo '<div style="font-size: 14px; color: red;">' . $this->error . '</div>';
}
;
?>
                     <?php
echo $this->formRow($form->get('csrf'));
echo $this->form()->closeTag();
?> 
                     <div class="text-center mt-5">
                        <p class="light-gray">Don't have an account? <a
				href="<?php  echo $this->url('user-register')?>">Sign Up</a></p>
                     </div>
                     <a
				href="<?php  echo $this->url("user-register", array("action"=>"reset-password"))?>">Forgot
				Password </a>
                  </div>
               </div>


</div>
















